In [1]:
import numpy as np

In [3]:
# just one array of elements
a = np.random.randn(5)
a

array([ 0.16667875, -0.48188364, -0.35143845, -0.26845092, -1.33514974])

In [4]:
expa = np.exp(a)
expa

array([1.18137469, 0.61761892, 0.70367516, 0.76456295, 0.26311877])

In [6]:
answer_softmax = expa / expa.sum()
answer_softmax

array([0.33463382, 0.1749455 , 0.19932161, 0.21656857, 0.0745305 ])

In [7]:
# these areprobabilities that add to 1
answer_softmax.sum()

1.0

In [9]:
# matrix (not one array, but many observations)
A = np.random.randn(100, 5)
A[1:5]

array([[-0.23845562, -0.73278475, -0.79009729,  0.47164012, -0.02031083],
       [ 1.38803129, -0.37522983,  0.55971557,  0.57446912,  0.71674058],
       [-1.85471841, -0.25436542, -0.03637523, -0.34920088, -1.1346599 ],
       [-0.44358015,  1.27271086,  3.57452541,  1.16232765,  0.58986135]])

In [10]:
# exponentiate them to make them positive
expA = np.exp(A)
expA[1:5]

array([[ 0.78784366,  0.48056886,  0.45380064,  1.60262053,  0.97989405],
       [ 4.00695373,  0.68713134,  1.75017463,  1.77618734,  2.04774785],
       [ 0.156497  ,  0.7754084 ,  0.9642784 ,  0.70525145,  0.32153146],
       [ 0.6417348 ,  3.57051863, 35.67768463,  3.19736697,  1.8037383 ]])

In [15]:
# axis=1 to sum over rows
# keepdims=True, since 2D matrix being divided by 1D vector
answerA_softmax = expA / expA.sum(axis=1, keepdims=True)
answerA_softmax[0:5]

array([[0.1070138 , 0.08645898, 0.47273459, 0.05799156, 0.27580108],
       [0.18301823, 0.11163746, 0.10541913, 0.37229312, 0.22763206],
       [0.39022961, 0.06691842, 0.17044618, 0.17297951, 0.19942627],
       [0.05354047, 0.2652813 , 0.32989715, 0.24127933, 0.11000175],
       [0.01429539, 0.07953744, 0.79476176, 0.07122505, 0.04018036]])

In [16]:
answerA_softmax.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
# check the denominator itself
expA.sum(axis=1, keepdims=True)[0:5]

array([[ 4.43774316],
       [ 4.30472774],
       [10.26819488],
       [ 2.92296671],
       [44.89104332]])

In [20]:
expA.sum(axis=1, keepdims=True).shape

(100, 1)